CREATE DATABASE IF NOT EXISTS book_store_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON book_store_db.* TO 'admin'@'%';

FLUSH PRIVILEGES;