spring:
  application:
    name: book_store

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/book_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
