spring:
  application:
    name: BookStore

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:mysql://localhost:3306/book_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
